[versions]
agp = "8.5.2"
kotlin = "1.9.24"
compileSdk = "35"
targetSdk = "28"
minSdk = "24"
androidxCoreKtx = "1.13.1"
androidxAppCompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.1.4"
androidxWebkit = "1.11.0"
junit4 = "4.13.2"
androidxTestExtJunit = "1.2.1"
androidxEspressoCore = "3.6.1"
zxingEmbedded = "4.3.0"
commonsCompress = "1.27.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "androidxWebkit" }
junit = { group = "junit", name = "junit", version.ref = "junit4" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspressoCore" }
zxing-android-embedded = { group = "com.journeyapps", name = "zxing-android-embedded", version.ref = "zxingEmbedded" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version.ref = "commonsCompress" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
